name: Build and Run openai-code-reviewer By Main Maven Jar

on:
  push:
    branches:
      - master-close
  pull_request:
    branches:
      - master-close
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn clean install
#
#      # Step 4: Copy SDK JAR from target directory
#      - name: Copy openai-code-review-sdk JAR
#        run: cp openai-code-review-sdk/target/openai-code-review-sdk-1.0.jar ./libs

      # Step 5: Optionally, run the JAR (example command)
      - name: Run code review
        run: java -jar openai-code-review-sdk/target/openai-code-review-sdk-1.0.jar
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_TOKEN }}
